[custom.all.z3]
type = "local"
path = "."
ipkg = "z3.ipkg"
test = "test/test.ipkg"

[custom.all.z3-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.cptr]
type = "github"
url = "https://github.com/Pandapip1/idris2-cptr"
commit = "latest:anyptr-support"
ipkg = "cptr.ipkg"
